### ISSUE TITLE
Error when querying schools

### ISSUE THREAD

**Issue by lmy0125** [Michigan-Tech-Courses/rate-my-professors#24]
I have been using this great source for my own project, but recently I found that it was not able to fetch data anymore, where ratings.searchSchool('michigan technological university') returns an error.
Using v2.2.1
Thank you

ClientError: Cannot query field "autocomplete" on type "Query".: {"response":{"data":null,"errors":[{"message":"Cannot query field \"autocomplete\" on type \"Query\".","locations":[{"line":6,"column":3}]}],"status":200,"headers":{}},"request":{"query":"\nquery AutocompleteSearchQuery(\n  $query: String!\n)\n{\n  autocomplete(query: $query) {\n    schools {\n      edges {\n        node {\n          id\n          name\n          city\n          state\n        }\n      }\n    }\n  }\n}","variables":{"query":"michigan technological university"}}}
    at /Users/lmy/Documents/Projects/BrightOcean/u-social/node_modules/graphql-request/dist/index.js:340:31
    at step (/Users/lmy/Documents/Projects/BrightOcean/u-social/node_modules/graphql-request/dist/index.js:63:23)
    at Object.next (/Users/lmy/Documents/Projects/BrightOcean/u-social/node_modules/graphql-request/dist/index.js:44:53)
    at fulfilled (/Users/lmy/Documents/Projects/BrightOcean/u-social/node_modules/graphql-request/dist/index.js:35:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  response: {
    data: null,
    errors: [ [Object] ],
    status: 200,
    headers: Headers { [Symbol(map)]: [Object: null prototype] }
  },
  request: {
    query: '\n' +
      'query AutocompleteSearchQuery(\n' +
      '  $query: String!\n' +
      ')\n' +
      '{\n' +
      '  autocomplete(query: $query) {\n' +
      '    schools {\n' +
      '      edges {\n' +
      '        node {\n' +
      '          id\n' +
      '          name\n' +
      '          city\n' +
      '          state\n' +
      '        }\n' +
      '      }\n' +
      '    }\n' +
      '  }\n' +
      '}',
    variables: { query: 'michigan technological university' }
  }
}

**Comment by codetheweb** [comment]
I noticed this was failing for michigantechcourses.com as well, happy to accept a PR for a fix.
